name: Produção

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
      tags:
        description: 'Tags' 
        
jobs:
  
  build-backend:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  
  build-frontend:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Build with Maven
        run: echo Frontend
  
  deploy-dev-backend:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment: prod
    needs: build-backend
    steps:
      - name: Deploy
        run: echo Prod, Backend


  deploy-dev-frontend:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment: prod
    needs: build-frontend
    steps:
      - name: Deploy
        run: echo Prod, Frontend
