name: Deploy Homologação

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'     
        required: true
        default: 'hmg'
      backend:
        type: boolean
        description: 'Back-end'
        default: 'true'
      frontend:
        type: boolean
        description: 'Front-end'
        default: 'true'
      migrations:
        type: boolean
        description: 'Migrations'
        default: 'false'
env:
  DISCORD_MESSAGE: |
      [{
        "title": "Notificação Deployment",
        "color": 1127128,
        "fields": [{
            "name": "Deploy",
            "value": "Homologação",
            "inline": true
          },
          {
            "name": "Branch",
            "value": "${{ github.event.inputs.branch }}",
            "inline": true
          },
          {
            "name": "Back-end",
            "value": "${{ github.event.inputs.backend == 'true' && ':white_check_mark:' || ':x:' }}"
          },
          {
            "name": "Front-end",
            "value": "${{ github.event.inputs.frontend == 'true' && ':white_check_mark:' || ':x:' }}"
          },
          {
            "name": "Migrations",
            "value": "${{ github.event.inputs.migrations == 'true' && ':white_check_mark:' || ':x:' }}"
          }               
        ]
      }] 

jobs:
  deploy_back_end:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Dump GitHub context
      env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
  discord_notification:
      runs-on: ubuntu-latest
      needs: deploy_back_end
      steps:
      - name: Discord Notification
        env:
          DISCORD_USERNAME: ${{ github.event.sender.login }}   
          DISCORD_AVATAR: ${{ github.event.sender.avatar_url }}
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/922863787365781524/HjtXWxAwk1UjoLOWd0XpwjiIsRrUars_b3vty6t7_zzgNyeJDCbR-TxudH2_dbsMlgkj      
          DISCORD_EMBEDS: ${{ toJSON(env.DISCORD_MESSAGE) }}
        uses: Ilshidur/action-discord@master
