name: Produção

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
      dev-version:
        description: 'Development Version'
      tags:
        description: 'Tags' 
        
jobs:
  
  get-changes:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: dev
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Pull changes from Dev
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        branch: ${{ github.ref }}
     
  release:
    runs-on: ubuntu-latest
    needs: get-changes
    steps:
    - uses: actions/checkout@main
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Set git user
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"  
        git pull --no-rebase
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Configure Maven
    - uses: s4u/maven-settings-action@v2.4.1
      with:
        servers: '[{"id": "github", "username": "${{ secrets.USER }}", "password": "${{ secrets.TOKEN }}"}]'    
    - name: Release
      run: mvn release:clean release:prepare release:perform -DlocalCheckout=true -DtagNameFormat=v${{ github.event.inputs.version }} -DreleaseVersion=${{ github.event.inputs.version }} -DdevelopmentVersion=${{ github.event.inputs.dev-version }} -Dusername=brunodutr -Dpassword=${{ secrets.TOKEN }}
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        branch: dev
     
  build-backend:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: release
    steps:
    - uses: actions/checkout@main
      with:
        ref: v${{ github.event.inputs.version }}
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  
  build-frontend:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: get-changes
    steps:
      - name: Build with Maven
        run: echo Frontend
  
  deploy-dev-backend:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    needs: build-backend
    steps:
      - name: Deploy
        run: echo Prod, Backend


  deploy-dev-frontend:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    needs: build-frontend
    steps:
      - name: Deploy
        run: echo Prod, Frontend
