name: Deploy Homologação

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'     
        required: true
        default: 'hmg'
      backend:
        type: boolean
        description: 'Back-end'
        default: 'true'
      frontend:
        type: boolean
        description: 'Front-end'
        default: 'true'
      migrations:
        type: boolean
        description: 'Migrations'
        default: 'false'
 
jobs:
  deploy_back_end:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Dump GitHub context
      env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
  discord_notification:
      runs-on: ubuntu-latest
      needs: deploy_back_end
      steps:
      - name: Discord notification
        env:
          DISCORD_USERNAME: ${{ github.event.sender.login }}   
          DISCORD_AVATAR: ${{ github.event.sender.avatar_url }}
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/922863787365781524/HjtXWxAwk1UjoLOWd0XpwjiIsRrUars_b3vty6t7_zzgNyeJDCbR-TxudH2_dbsMlgkj       
          DISCORD_EMBEDS: '[{"title":"Deploy", "description": "Deploy: Homologação\nBranch: ${{ github.event.inputs.branch }}\n\n:white_check_mark: Back-end\n:white_check_mark: Front-end\n:white_check_mark: Migrations", "color":1127128 }]'
        uses: Ilshidur/action-discord@master
